#!/bin/bash

#sed    "s/muscl/amont/"                 PAR_VEF_P0P1_g_muscl.data   >  PAR_VEF_P0P1_g_amont.data
sed    "s/muscl/negligeable/; s/Fields dt_post 40/Fields dt_post 400/" PAR_VEF_P0P1_g_muscl.data   >  PAR_VEF_P0P1_g_negligeable.data
sed    "s/muscl/Ef_stab { alpha 0.2 }/" PAR_VEF_P0P1_g_muscl.data   >  PAR_VEF_P0P1_g_ef_stab.data

sed    "s/+p_hydro//"                                PAR_VEF_P0P1_g_muscl.data   >  PAR_VEF_P0P1_gx_muscl.data
#cp PAR_VEF_P0P1_g_muscl.data  PAR_VEF_P0P1_gx_muscl.data
sed -i "/gravite/c gravite champ_uniforme 3 -9.81 0. 0." PAR_VEF_P0P1_gx_muscl.data
sed    "s/muscl/Ef_stab { alpha 0.2 }/"                             PAR_VEF_P0P1_gx_muscl.data  >  PAR_VEF_P0P1_gx_ef_stab.data
sed    "s/muscl/negligeable/; s/Fields dt_post 80/Fields dt_post 500/" PAR_VEF_P0P1_gx_muscl.data   >  PAR_VEF_P0P1_gx_negligeable.data



liste="PAR_VEF_P0P1_g_muscl PAR_VEF_P0P1_g_negligeable PAR_VEF_P0P1_g_ef_stab PAR_VEF_P0P1_gx_muscl PAR_VEF_P0P1_gx_ef_stab PAR_VEF_P0P1_gx_negligeable"
for i in $liste
do
        mkdir -p $i
        cp mesh_gmsh.med mesh.data $i.data $i
        cp post_run pre_run propertiesGeometry.py $i
        cd $i
        sed -i "s/PAR_VEF_P0P1_g/$i/g" propertiesGeometry.py
        cd ..
done



