#!/bin/bash
gunzip -c $TRUST_ROOT/tests/Reference/Collecteur/collecteur_chaud.geom.gz > collecteur_chaud.geom
pcs="amg block_amg"
for pc in $pcs
do
   make_PAR.data $pc.data
   cp PAR_$pc.data $pc.data
done
exit 0
